# Site settings
title: Thoughts of a spatial geek
email: aberenyi@gislab.hu
url: http://blog.gislab.hu

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/AttilaBerenyiDr
  - title: github
    url: https://github.com/aberenyi

disqus:
  short_name: gislab

google_analytics:
  tracking_id: 'UA-67413135-1'

# Build settings
exclude:
  - "*.less"
  - "*.jade"
markdown: kramdown
permalink: pretty
