# Site settings
title: GISLab Blog
email: aberenyi@gislab.hu
url: http://gislab.hu
description: "Thoughts of a GIS geek"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/AttilaBerenyiDr
  - title: github
    url: https://github.com/aberenyi

# Build settings
exclude:
  - "*.less"
  - "*.jade"
markdown: kramdown
permalink: pretty
